<?php
namespace MMHK\Debugbar\Middleware;


use Illuminate\Contracts\Container\Container;
use MMHK\Debugbar\LaravelDebugbar;

class Debugbar extends \Barryvdh\Debugbar\Middleware\Debugbar {



    public function __construct(Container $container, LaravelDebugbar $debugbar)
    {
        parent::__construct($container, $debugbar); // TODO: Change the autogenerated stub
    }
} 