<?php
namespace MMHK\Debugbar\Middleware;


use Illuminate\Contracts\Container\Container;

class Debugbar extends \Barryvdh\Debugbar\Middleware\Debugbar {



    public function __construct(Container $container, \MMHK\Debugbar\Debugbar $debugbar)
    {
        parent::__construct($container, $debugbar); // TODO: Change the autogenerated stub
    }
} 