<?php
namespace MMHK\Debugbar;


use DebugBar\DebugBar;

class JavascriptRenderer extends \Barryvdh\Debugbar\JavascriptRenderer {

    public function __construct(DebugBar $debugBar, $baseUrl = null, $basePath = null)
    {
        parent::__construct($debugBar, $baseUrl, $basePath); // TODO: Change the autogenerated stub

        $this->setOptions(app('config')->get('debugbar.jsrender', array()));
    }


    public function dumpAssetsToString($type)
    {
        $files = $this->getAssets($type);

        $content = '';
        foreach ($files as $file) {
            $content .= file_get_contents($file) . "\n";
        }

        if ($type == 'js') {
            if ($this->isRequireJsUsed()) {
                $content = "define('debugbar', [], function(){\r\n" . $content . "\r\n return PhpDebugBar; \r\n});";
            }
        }

        return $content;
    }

    public function render($initialize = true, $renderStackedData = true)
    {
        return parent::render($initialize, $renderStackedData); // TODO: Change the autogenerated stub
    }


} 