<?php
namespace MMHK\Debugbar;


use Illuminate\Session\SessionManager;

class ServiceProvider extends \Barryvdh\Debugbar\ServiceProvider {

    /**
     * 重写中间件引用
     * @param string $middleware
     */
    protected function registerMiddleware($middleware)
    {
        $kernel = $this->app['Illuminate\Contracts\Http\Kernel'];
        $kernel->pushMiddleware('MMHK/Debugbar/Middleware/Debugbar');
    }

    /**
     * 重写 覆盖 debugger 实例的注入
     */
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->app->singleton('debugbar', function ($app) {
                $debugbar = new LaravelDebugbar($app);

                if ($app->bound(SessionManager::class)) {
                    $sessionManager = $app->make(SessionManager::class);
                    $httpDriver = new \Barryvdh\Debugbar\SymfonyHttpDriver($sessionManager);
                    $debugbar->setHttpDriver($httpDriver);
                }

                return $debugbar;
            }
        );
    }


} 